project:
  type: website
  output-dir: docs

website:
  title: "Jean Carlos's Data Science Blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/jeancmaia
format:
  html:
    theme: journal
    css: styles.css



